vich_uploader:
    db_driver: orm

    mappings:
        regions:
            uri_prefix: /images/regions
            upload_destination: '%kernel.project_dir%/public/images/regions'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
